---
# Source: harbor-operator/templates/validatingwebhookconfiguration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: 'rackspace-staging/harbor-operator-serving-cert'
  name: 'harbor-operator-validating-webhook-configuration'