apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velero
spec:
  encryptedData:
    cloud: AgCOV4qdU1m4p2teqEZSm6TrqLJ7MWhIhBNwn2po9nufgt3llQS8xvsMETAuJBSD55lX7agdpRn3ysGEP3QtcsKiQST38TfHmSC/pCVMCcO3Tz0J0M70q3FaCGo12Y7NSV06PYoSC8+c9L8ZpCNX8s2gJueTeAtHMxB4lbp4yDrwVb/NFyzy0bo1sungjWFfw9sIs2plv5ZHIS3BdVqpDszLHfEBstzwLIvH7KjAz8GGOCaCGA9WOCxmNvOHWYeOKMyIRvKplBZ81bU9BoWlIQ8+4KL4+QzT5jphMxCAiEqFjEE8BMZzKp2EhqEd9SpMjrAGCE7q3zZ93K8DxYxWQ3xi/kzQynBUzj8RVpU9tfNXYUcqpU2WSUM/epLpB/axV7zS5wQFrUnorbBz+YD4W5f7i5e9yviLYYX2MGQfjugBFZFy61SiGeoS5guDFb2I6M/mfWu/ClGvPEBRE/uieiMKXNUvm7GpymXfZ8Qxa+M7TogGbES1q26cgXcy2LDTGOtik+XlxwW6nT596imcF737/J4VgdP+7OOu6naI05Ftufvtx1oefqF3OkfYF7mRxq0YatLpPoSMVAICZ5NUSciEMpadCHvVzvOL6HM54yNSi+rzWfil3a7oHQpmcVSuhDpznvFWxnNL+pWoQbsp8HTvyaAC0mwv2fvGGbg+JwdOuxAoapA1I+ODr6TurvBM9n3YvFD1cusCVYdXITgpKXRbl077tiiumVjw6bofHocQQcNqD2G53sfqfpFBwekzPXaOmISiSKZm9UnReoqC153OYNJt6gY+Y0XNjVH7jeE31fCKzalGc99rpPKnkoK565r8Zhc47vQXsC5T5mdl4Q5AxcsJVA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-2.27.0
      name: velero
    type: Opaque

