---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
    - '../../../../mpk-apps/velero/'
    - './backupstoragelocation.yaml'
    - './encrypted-secret.yaml'

patchesStrategicMerge:
    - './deployment.yaml'
