---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alpha-rke-cluster-harbor-operator
  namespace: argocd
  labels:
    env: alpha-rke-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: alpha-rke-cluster
  source:
    repoURL: https://github.com/vish6760/alpha-managed-services.git
    path: alpha-rke-cluster/overlays/rackspace-staging/harbor-operator
    targetRevision: HEAD

  destination:
    name: alpha-rke-cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
