apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: route53-secret
spec:
  encryptedData:
    secret-access-key: AgBhpfKzKzxh+fZQ9fb4GnlLqmpUCjFOHesKfIunLzxMKexCA2NegKU283i3gA4oZMYirz/dM2GsHgSuUqdQC0MdGsvC4UonTLyYbipoYH2cytDtYavZAl6GHoD9xYBVs5U9OlKhQMhUh38MeHnCxVKMY9xJEWx+qnpoWXq21cOu87PePqOZxfi98Kt/D669msmb+EuJ3gDsaKBUV83H++gd3JpKUxKE3zRu6uId8niRZKTFcMkLVIrsVtyo+lEPkx/7ktrlfo44Ia3PVIMr6E7e6qgIJLeH/NXGTGxXFKBnCKYzmlfQz4UK5/Slvoo9NhTL/h+9KrMYovbgmKreKwphMmrQ780X6wFrp9H1UYK8i9Rb9mttmQEUNb7xucgs8YgvvfRxnQUeKVRkQZWjjb5MoTTeQu1hdlqGwxB6PClEiv/sF8+hNC2BKgFeZs47ab6nam86eGXv1xLHKqYP5zhSLKaMnzgp8VRkMlqsC5je1A9h1BWzH6PTBgz/qQqk8fVXsgEPbwrXnnEFvVW3ewcZu9f90XuMnfIbXWf1OSdDW8Diyd+GVMJNABdVkNn5qM/mPEVHvqoVqPgOWkiRioiTVcXYHr741cD5SW2d0xLxNxspfPIDvA7Auo+SENMyVWvWQnywElMXeIIgcu2hPVE7oL4Sx8xX5mYUkKgT0M4VUJg8I/n5+kc8m5drCHH36ya9Uz5K6z6qh2n0vGDRjy0N21l7a6ex2uOWO1zbb0VSiKbFB7qMzAlfRQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: route53-secret
    type: Opaque

