apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
spec:
  encryptedData:
    credentials: AgBSIJsulE3x0FzlOjNrjeaOI4wtXx7ZQf3vg8wDSL14EE7xhbB+oNxXhW0JGKCphSGqTsN8g4odhlMYdokmddmDtJPayl662Abg0clUnAw0EwRkecgnM+UVSY/qtiFelWm8Rb64SJPs/zyf5McPFrQejsDl7UtMl3GsUuWMvF0p1FBSY/wGfFfrIxGKfL8pFuiLmHX3GTtulrBXG3XT/q5ZeUID35Z/vXMdhefehYJYiC9w+Zf+NValpOePLOkfzSbBYn/7vz4Phpt0BMEA6MYjkeLQpBobY8JdmM5UUmJKrpcn6Mrz8i9AJXgYdrakUcl1RhV/WicLzY/v/WjCkeghqvS3UMKWmSrBKXyt/QB6mPLiHJKOCdcFZ/j3hag6mtrXLg7wKYjCc5pemyKxvlnQsaoNYwj2qw0Yb0aVlME86GgxhbKJAy8gVomHEcrVpI5y9k9JF/Dnz+D4PymyyPsFVR5EAQMhTGJWcoNW0+36pezIMH/4uM0FfOppSHcNJ+YfJlwtWsgn1NmfBh+pzla2cbPZ5oLqAXRfC8A6Op7iaMze1XEBkwO7e6gC3zyZH9/uoY/51FXWbNC88grUN/1oeYPn0+dDXaOsnq3jGYbGpsMwIHvMF0mniyEtylw5v0yE90kzQ0vzwNpiG5yaR5MWAxZriUDVd+HfLgy0Ke6QwjvoDoWGF7/TDeGbrtIN1mweJJ0Ltk+lXzDCzz7Wy4I42IknwwnlGM1jj6/248KeFEJkXBlzABIX2znVSxxwfX0wCx1uncaE5ys5Ob9zIN/6N+dZ+uTFsjmqhFE8fv5nqQzwtDanXFWFI0EsrAiWDOD5GXhucfj95yeh+pYjgZuejQ/mwA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-5.4.11
      name: external-dns
    type: Opaque

