---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
    - '../../../../mpk-apps/harbor/'
    - './certificate.yaml'
    - './harbor-cr.yaml'
    - './pvc.yaml'
    - './encrypted-secret.yaml'

